### ISSUE TITLE
安装对接k8s 报错exit status 2

### ISSUE THREAD

**Issue by cleveryg** [goodrain/rainbond-ansible#100]
安装操作系统内核版本为centos 3.10.0-957.21.3.el7.x86_64
k8s版本为1.13.4
docker版本为 18.09.6
运行初始化命令为 grctl init --iip xx.xx.xx.xx --deploy-type thirdparty
报错具体日志为：
Ansible FAILED! => playbook: hack/thirdparty/setup.yaml; TASK: prepare : minimum kernel version; message: {"msg": "The conditional check 'ansible_kernel is version(docker_kernel_min_version, \"<\")' failed. The error was: template error while templating string: no test named 'version'. String: {% if ansible_kernel is version(docker_kernel_min_version, \"<\") %} True {% else %} False {% endif %}\n\nThe error appears to have been in '/opt/rainbond/rainbond-ansible/roles/prepare/tasks/check.yml': line 71, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: minimum kernel version\n  ^ here\n"}

**Comment by 1909490139** [comment]
暂不支持对接k8s
