### ISSUE TITLE
高可用模式下，管理节点未生效

### ISSUE THREAD

**Issue by linyx-7** [goodrain/rainbond-ansible#103]
请提供如下信息：
- 安装环境信息(云服务商或者本地虚拟环境，系统版本，内核版本，配置信息等)阿里云ecs centos7.4
- 安装类型(单机,离线,使用版本信息等) 5.1.5在线安装
- ansible安装日志 (`/opt/rainbond/rainbond-ansible/log/`)
- 能否复现，如何复现
- 如果可以提供相关截图
安装了三个管理节点一个计算节点，在第一个安装的管理节点上可以正常执行grctl cluster ，集群的四个节点都是正常状态。当关闭第一个管理节点后，在其他管理节点上执行grctl cluster都异常，The current cluster api server is not working properly.
You can query the service log for troubleshooting.
Exec Command: journalctl -fu rbd-api
当第一个管理节点异常后，其他管理节点能否自动可用？还是即使第一个管理节点不关机，我也可用从三个节点上访问7070端口，或者执行grctl cluster命令。谢谢。

[root@BackServer01 ~]# journalctl -fu rbd-api
-- Logs begin at Thu 2019-08-01 06:16:59 CST. --
Aug 01 11:20:11 BackServer01 bash[2954]: time="2019-08-01T11:20:11+08:00" level=info msg="update event handle core success,handle core count:2, event server count:2"
Aug 01 11:20:11 BackServer01 bash[2954]: time="2019-08-01T11:20:11+08:00" level=info msg="Update event server endpoint,172.26.1.2:6366"
Aug 01 11:20:11 BackServer01 bash[2954]: time="2019-08-01T11:20:11+08:00" level=info msg="Update event server endpoint,172.26.1.1:6366"
Aug 01 11:20:11 BackServer01 bash[2954]: time="2019-08-01T11:20:11+08:00" level=info msg="update event handle core success,handle core count:2, event server count:2"
Aug 01 11:20:18 BackServer01 bash[2954]: time="2019-08-01T11:20:18+08:00" level=error msg="watch chan error: etcdserver: mvcc: required revision has been compacted"
Aug 01 11:20:18 BackServer01 bash[2954]: time="2019-08-01T11:20:18+08:00" level=error msg="watch chan error: etcdserver: mvcc: required revision has been compacted"
Aug 01 11:20:19 BackServer01 bash[2954]: time="2019-08-01T11:20:19+08:00" level=info msg="Update event server endpoint,172.26.1.1:6366"
Aug 01 11:20:19 BackServer01 bash[2954]: time="2019-08-01T11:20:19+08:00" level=info msg="update event handle core success,handle core count:1, event server count:1"
Aug 01 11:20:19 BackServer01 bash[2954]: time="2019-08-01T11:20:19+08:00" level=info msg="Update event server endpoint,172.26.1.1:6366"
Aug 01 11:20:19 BackServer01 bash[2954]: time="2019-08-01T11:20:19+08:00" level=info msg="update event handle core success,handle core count:1, event server count:1"

**Comment by barnettZQG** [comment]
你的问题原因是region.goodrain.me域名解析地址为第一个节点的IP地址。
做高可用时需要设置VIP或上层的负载均衡。
详细的高可用安装文档将在5.1.6版本发布。
