### ISSUE TITLE
Rainbond 5.1.5 grctl命令维护inventory/hosts文件功能

### ISSUE THREAD

**Issue by olonglongo** [goodrain/rainbond-ansible#105]
需求：
1.grctl命令根据集群API获取集群状态动态维护inventory/hosts文件
2.inventory/hosts文件中主机名称规范化如(master->manage,worker->compute)

**Comment by barnettZQG** [comment]
5.1.6版本：
初始化安装第一个节点时：inventory/hosts 文件由setup脚本生成。
后续添加安装节点时由grctl命令行或node服务维护。
inventory/hosts文件中维护以下组：
[all] 全部主机信息
[manage] 管理节点主机列表，根据添加实际排序，第一台主机认为为第一个节点
[compute] 计算节点主机
[gateway] 网关节点主机
[etcd]  ETCD所在主机
[new-manage]  新安装管理节点
[new-compute]  新安装计算节点
[new-gateway]  新安装网关节点

https://github.com/goodrain/rainbond/pull/349
