### ISSUE TITLE
签署证书之前，要清理证书目录内的文件，否则报错

### ISSUE THREAD

**Issue by dazuimao1990** [goodrain/rainbond-ansible#116]
请提供如下信息：
- 安装环境信息(云服务商或者本地虚拟环境，系统版本，内核版本，配置信息等)
- 安装类型(单机,离线,使用版本信息等)
- ansible安装日志 (`/opt/rainbond/rainbond-ansible/log/`)
- 能否复现，如何复现
- 如果可以提供相关截图
签署证书之前，要清理证书目录内的文件，否则报错
需要优化，添加一个任务，在生成证书之前，清理证书目录内容

**Comment by 1909490139** [comment]
无法复现该问题
