### ISSUE TITLE
重启服务器后，nfs_server启动不成功

### ISSUE THREAD

**Issue by mayizhenxu** [goodrain/rainbond-ansible#124]
![image](https://user-images.githubusercontent.com/49012273/67545431-a1b29300-f72b-11e9-9c5c-33357171ea9d.png)

**Comment by 1909490139** [comment]
手动执行以下操作处理本问题：
重启rpcbind和nfs服务
systemctl restart rpcbind.service;
systemctl restart nfs-server.service;
设置rpcbind和nfs开机自启动
systemctl enabled rpcbind.service;
systemctl enabled nfs-server.service
