### ISSUE TITLE
安装时一直卡在推送镜像到镜像仓库

### ISSUE THREAD

**Issue by hubyao** [goodrain/rainbond-ansible#145]
使用ui界面安装时一直卡在倒数第二步
推送镜像到远程仓库，能否手动改动仓库地址到阿里云，还是有其他解决方案
![image](https://user-images.githubusercontent.com/32606145/81791346-34d0e000-9539-11ea-9dc9-44df71566ccd.png)

**Comment by barnettZQG** [comment]
@stepGitHub 提交5.2相关安装问题请移步 https://github.com/goodrain/rainbond-operator/issues 
当前仓库属于5.1版本安装脚本，目前已不再维护。
