### ISSUE TITLE
precheck::check_disk不支持超过1T的硬盘

### ISSUE THREAD

**Issue by mskmkt0704** [goodrain/rainbond-ansible#43]
安装程序无法识别以T为单位的硬盘,setup.sh的precheck::check_disk判断有误

![image](https://user-images.githubusercontent.com/10786748/53863222-938cf680-4024-11e9-82f6-23fd16163ebb.png)

**Comment by mskmkt0704** [comment]
似乎是操作系统版本的问题..

**Comment by ysicing** [comment]
磁盘大小检查处理有问题已经修复 /🐶
