### ISSUE TITLE
node二进制与系统nodejs命令 /usr/bin/node 冲突

### ISSUE THREAD

**Issue by dazuimao1990** [goodrain/rainbond-ansible#58]
请提供如下信息：
- 安装环境信息(云服务商或者本地虚拟环境，系统版本，内核版本，配置信息等)
- 安装类型(单机,离线,使用版本信息等)
- ansible安装日志 (`/opt/rainbond/rainbond-ansible/log/`)
- 能否复现，如何复现
- 如果可以提供相关截图

在rainbond中同时存在nodejs的环境，则会影响到nodejs的命令使用。

**Comment by ysicing** [comment]
暂不考虑这个
