### ISSUE TITLE
Init Data Region if migrate_ui_ok 步骤安装失败

### ISSUE THREAD

**Issue by JuicyxLemon** [goodrain/rainbond-ansible#73]
请提供如下信息：
- 安装环境信息(云服务商或者本地虚拟环境，系统版本，内核版本，配置信息等)
- 安装类型(单机,离线,使用版本信息等)
- ansible安装日志 (`/opt/rainbond/rainbond-ansible/log/`)
- 能否复现，如何复现
- 如果可以提供相关截图

安装环境：华为云ECS, Debian 9.9 x64
服务器配置：4核8G 140G磁盘
内核版本：Linux debian 4.9.0-9-amd64 #1 SMP Debian 4.9.168-1 (2019-04-12) x86_64
安装类型：单机
安装启动命令行：./grctl init --iip 172.30.9.172 --eip [已隐藏]
能否复现：能，多次安装（Ubuntu 19.04和Debian 9均做测试），甚至在纯净系统环境下安装依然得到同样结果

相关日志文件（公网IP相关信息已脱敏处理）：
/opt/rainbond/rainbond-ansible/log/rainbond.log： https://paste.ubuntu.com/p/BX7ZJrFsxG/
/opt/rainbond/rainbond-ansible/log/fail.log： https://paste.ubuntu.com/p/4kgGnDysBC/

联系方式（仅作为issue跟进使用，非相关请勿打扰）：
E-mail： ilemonrain@ilemonrain.com
Telegram： https://t.me/ilemonrain

**Comment by ysicing** [comment]
我确定一下Debian & Ubuntu。
目前华为云上仅测试过CentOS

可以参考 [初始化数据中心](https://www.rainbond.com/docs/user-operations/op-guide/table_region_tenants_not_exist/#排查方式)

**Comment by JuicyxLemon** [comment]
已通过测试确认故障原因，也当是给后来人一个小小的提醒吧：

自己服务器上的IP，请注意不要和 172.30.42.1/16 （也就是172.30.0.0/16） 这个段发生撞段，如果撞段了请更改自己服务器上的IP避开这个段就可以了
