### ISSUE TITLE
无法同时安装计算节点+网关

### ISSUE THREAD

**Issue by 651016236** [goodrain/rainbond-ansible#77]
请提供如下信息：
- 安装环境信息 centos7.4
无法同时安装计算节点+网关
grctl node add --host compute01 --iip xx.xx.xx.xx -p <密码> --role compute,gateway
提示only compute or gateway

**Comment by olonglongo** [comment]
现在安装脚本已经修改为支持多role的条件支持。eg: manage,compute

**Comment by barnettZQG** [comment]
5.1.6 版本中发布。
