### ISSUE TITLE
无法安装 报错为exit status 56

### ISSUE THREAD

**Issue by TrustAsia** [goodrain/rainbond-ansible#79]
root@Docker:~# ./grctl init --enable-check disable --iip 172.16.0.210 --enable-exdb true --exdb-type mysql --exdb-host 172.16.0.100 --exdb-port 3307 --exdb-user root --exdb-passwd 123123123 --enable-excsdb-only true --excsdb-host 172.16.0.100 --excsdb-port 3307 --excsdb-user root --excsdb-passwd 123123123
Download the installation configuration file remotely...
info: Start clone source code from 
Enumerating objects: 571, done.
Counting objects: 100% (571/571), done.
Compressing objects: 100% (435/435), done.
Total 571 (delta 103), reused 376 (delta 61), pack-reused 0
Initializes the installation of the first node...
 --- Preparation before installation... --- 
 >  Notice  将从互联网下载离线镜像文件(约2GB)，下载速度取决于当前机器网络带宽 
 >  Installation type  online 
 >  Deployment type  onenode 
 >  Rainbond Version  5.1(v5.1.4-release) 
 --- Detect debian required packages... --- 
[/opt/rainbond/rainbond-ansible]# apt-get update -q 
Ign:1 https://mirrors.tuna.tsinghua.edu.cn/debian stretch InRelease
Hit:2 https://mirrors.tuna.tsinghua.edu.cn/debian stretch-updates InRelease
Hit:3 https://mirrors.tuna.tsinghua.edu.cn/debian stretch-backports InRelease
Hit:4 https://mirrors.tuna.tsinghua.edu.cn/debian-security stretch/updates InRelease
Hit:5 https://mirrors.tuna.tsinghua.edu.cn/debian stretch Release
Reading package lists...
 OK   

[/opt/rainbond/rainbond-ansible]# apt-get install -y -q sshpass python-pip uuid-runtime pwgen expect curl net-tools git 
Reading package lists...
Building dependency tree...
Reading state information...
curl is already the newest version (7.52.1-5+deb9u9).
expect is already the newest version (5.45-7+deb9u1).
git is already the newest version (1:2.11.0-3+deb9u4).
net-tools is already the newest version (1.60+git20161116.90da8a0-1).
pwgen is already the newest version (2.07-1.1+b1).
python-pip is already the newest version (9.0.1-2+deb9u1).
sshpass is already the newest version (1.06-1).
uuid-runtime is already the newest version (2.29.2-1+deb9u1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
 OK   

[/opt/rainbond/rainbond-ansible]# pip install ansible -i https://pypi.tuna.tsinghua.edu.cn/simple 
Requirement already satisfied: ansible in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied: PyYAML in /usr/local/lib/python2.7/dist-packages (from ansible)
Requirement already satisfied: jinja2 in /usr/local/lib/python2.7/dist-packages (from ansible)
Requirement already satisfied: cryptography in /usr/lib/python2.7/dist-packages (from ansible)
Requirement already satisfied: MarkupSafe>=0.23 in /usr/local/lib/python2.7/dist-packages (from jinja2->ansible)
 OK   

 >  internal ip  172.16.0.210 
 --- Prepare check --- 
 >  prepare check uid  passed 
 >  prepare check system  passed 
 >  prepare check iip  passed 
 >  prepare check ip cidr  passed 
 >  prepare check network  passed 
 >  prepare check port  passed 
 >  prepare check disk  passed 
 >  Use database type  external/mysql 
 >  database region info  user:root/123123123 host:172.16.0.100:3307 
 >  database console info  user:root/123123123 host:172.16.0.100:3307 
 >  Generate the default configuration  62984d56-f94b-2e98-4c37-0cd9594b5a93/jim5feiluxieb3aishai5aiK4or6Hemu 
 >  nameserver  172.16.0.1 
 >  docker version  18.06 

 >  storage type  nfs 
 >  storage args  /grdata nfs rw 0 0 
exit status 56
root@Docker:~# 

操作系统版本为

root@Docker:~# cat /etc/issue
Debian GNU/Linux 9 \n \l

root@Docker:~# 

内核版本为

root@Docker:~# uname -a
Linux Docker 4.9.0-9-amd64 #1 SMP Debian 4.9.168-1+deb9u2 (2019-05-13) x86_64 GNU/Linux
root@Docker:~# 

机器为虚拟机 宿主机为ESXi 6.7
虚拟化技术为

root@Docker:~# virt-what
vmware
root@Docker:~# 

宿主机版本为

[root@ESXi:~] uname -a
VMkernel ESXi.lan 6.7.0 #1 SMP Release build-10302608 Oct  2 2018 19:36:37 x86_64 x86_64 x86_64 ESXi
[root@ESXi:~]

**Comment by olonglongo** [comment]
以日志来看，请检查一下所使用的mysql连接权限。
