### ISSUE TITLE
Failed to update apt cache

### ISSUE THREAD

**Issue by damozhiying** [goodrain/rainbond-ansible#80]
TASK [prepare : rm ubuntu lxd & ufw package] ***************************************************************************************************************************************************************
ok: [4c4c4544-0039-5610-8039-b3c04f4a3932]
Tuesday 18 June 2019  13:57:28 +0800 (0:00:00.701)       0:00:06.651 ********** 

TASK [prepare : install ubuntu package] ********************************************************************************************************************************************************************
fatal: [4c4c4544-0039-5610-8039-b3c04f4a3932]: FAILED! => {"changed": false, "msg": "Failed to update apt cache: "}

PLAY RECAP *************************************************************************************************************************************************************************************************
4c4c4544-0039-5610-8039-b3c04f4a3932 : ok=16   changed=2    unreachable=0    failed=1    skipped=20   rescued=0    ignored=0   

ERROR MESSAGE SUMMARY **************************************************************************************************************************************************************************************
[4c4c4544-0039-5610-8039-b3c04f4a3932]: Ansible FAILED! => playbook: setup.yml; TASK: prepare : install ubuntu package; message: {"changed": false, "msg": "Failed to update apt cache: "}

Ask for help:
Contact us: rainbond@goodrain.com
Community: https://t.goodrain.com
It seems that you encounter some problems. You can send an email to the above email address, attached with the rainbond-ansible/inventory/hosts and rainbond-ansible/log/rainbond.log files and the error message, or new issue on https://github.com/goodrain/rainbond-ansible/issues. We'll try our best to help you deploy a Rainbond cluster. Thanks. :-)
Tuesday 18 June 2019  13:57:29 +0800 (0:00:00.563)       0:00:07.215 ********** 
=============================================================================== 
Gathering Facts ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 1.88s
prepare : rm ubuntu lxd & ufw package --------------------------------------------------------------------------------------------------------------------------------------------------------------- 0.70s
bootstrap : gather facts ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 0.61s
prepare : install ubuntu package -------------------------------------------------------------------------------------------------------------------------------------------------------------------- 0.56s
bootstrap : start irqbalance service ---------------------------------------------------------------------------------------------------------------------------------------------------------------- 0.37s
bootstrap : setting present kernel params ----------------------------------------------------------------------------------------------------------------------------------------------------------- 0.33s
prepare : populate rainbond into hosts file --------------------------------------------------------------------------------------------------------------------------------------------------------- 0.24s
prepare : set_fact ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 0.22s
bootstrap : setting absent kernel params ------------------------------------------------------------------------------------------------------------------------------------------------------------ 0.20s
bootstrap : modify debian irqbalance configuration file --------------------------------------------------------------------------------------------------------------------------------------------- 0.19s
prepare : Determine which mountpoint deploy dir exists on ------------------------------------------------------------------------------------------------------------------------------------------- 0.19s
bootstrap : check centos configuration file exists -------------------------------------------------------------------------------------------------------------------------------------------------- 0.19s
bootstrap : check debian configuration file exists -------------------------------------------------------------------------------------------------------------------------------------------------- 0.12s
prepare : Preflight check - Check Linux kernel overcommit_memory parameter -------------------------------------------------------------------------------------------------------------------------- 0.12s
prepare : Stop if cpu is sufficient for workers ----------------------------------------------------------------------------------------------------------------------------------------------------- 0.06s
prepare : Create the yum source backup folder ------------------------------------------------------------------------------------------------------------------------------------------------------- 0.06s
prepare : Check https::proxy in /etc/apt/apt.conf --------------------------------------------------------------------------------------------------------------------------------------------------- 0.06s
prepare : Add http_proxy to /etc/apt/apt.conf if http_proxy is defined ------------------------------------------------------------------------------------------------------------------------------ 0.06s
prepare : Check http::proxy in /etc/apt/apt.conf ---------------------------------------------------------------------------------------------------------------------------------------------------- 0.06s
prepare : Stop if memory is too small for workers --------------------------------------------------------------------------------------------------------------------------------------------------- 0.05s
exit status 2

**Comment by damozhiying** [comment]
[ansible.log](https://github.com/goodrain/rainbond-ansible/files/3304057/ansible.log)

**Comment by olonglongo** [comment]
看报错怀疑是ubuntu/debian源的问题导致的，请执行`apt-get update`查看一下结果。

**Comment by barnettZQG** [comment]
我将关闭这个问题，如果未解决请重新打开
