### ISSUE TITLE
grctl node add 支持多种角色组合

### ISSUE THREAD

**Issue by GLYASAI** [goodrain/rainbond-ansible#88]
如题，安装时应可以指定多个角色一起安装，比如 “manage+gateway”、“compute+gateway” 、 “compute+manage+gateway” “gateway”

![image](https://user-images.githubusercontent.com/21967570/61301647-e23e6e80-a816-11e9-88fc-3fa8e7b715a1.png)

grtctl命令行已支持，现在安装脚本支持。

**Comment by olonglongo** [comment]
通过在“scripts/node.sh“与“setup.sh“脚本中修改ansible调用参数直接对noderule进行传参,并删除ansible role中第二次获取noderule参数的规则：
“roles/prepare/defaults/main.yml“与“roles/node/core/defaults/main.yml“

通过离线与在线测试安装脚本已经支持多个角色一起安装
<img width="962" alt="屏幕快照 2019-07-24 下午7 34 32" src="https://user-images.githubusercontent.com/37605428/61790610-4500bd00-ae4a-11e9-83ab-5219584cc6d6.png">

**Comment by linyx-7** [comment]
如果已经安装完成了，怎么才能给manage添加gateway角色，或者gateway添加manage角色？

**Comment by barnettZQG** [comment]
@linyx-7 
已安装的节点安装脚本不支持再新加角色。

**Comment by barnettZQG** [comment]
灵活部署节点属性功能在5.1.6版本中发布
