### ISSUE TITLE
升级5.1.5版本没办法新增节点

### ISSUE THREAD

**Issue by dazuimao1990** [goodrain/rainbond-ansible#89]
请提供如下信息：
- 安装环境信息(云服务商或者本地虚拟环境，系统版本，内核版本，配置信息等)
- 安装类型(单机,离线,使用版本信息等)
- ansible安装日志 (`/opt/rainbond/rainbond-ansible/log/`)
- 能否复现，如何复现
- 如果可以提供相关截图

原有平台升级至 5.1.5 后，执行扩容节点时会报错
![image](https://user-images.githubusercontent.com/33855684/61679072-92d8d080-ad37-11e9-99ed-b7fcf2dfdb30.png)

**Comment by dazuimao1990** [comment]
这是已知的bug，会尽快修正

**Comment by barnettZQG** [comment]
节点安装时首先构建相关变量，master_ip 就是其中一项，第一个管理节点的IP地址。
这里的错误是在过去版本中 /opt/rainbond/rainbond-ansible/roles/rainvar/defaults/main.yml配置文件定义的是 MASTER_IP 而不是master_ip。需要修改它。
```
MASTER_IP: "{{hostvars[groups['master'][0]]['ip']}}"
```
修改为:
```
master_ip: "{{hostvars[groups['master'][0]]['ip']}}"
```

**Comment by barnettZQG** [comment]
我将关闭这个问题，如果未解决请重新打开。
