### ISSUE TITLE
阿里云服务器在线安装报错，换了一台同样错误。

### ISSUE THREAD

**Issue by dazuimao1990** [goodrain/rainbond-ansible#90]
请提供如下信息：
- 安装环境信息(阿里云)
- 安装类型(单机)
- ansible安装日志 (`/opt/rainbond/rainbond-ansible/log/`)
- 能否复现，如何复现
- 如果可以提供相关截图

### 阿里云服务器在线安装报错，换了一台同样错误。
```bash
TASK [node/init : init rainbond] ******************************************************************************************************************************************************************************
[ba1b4b4c-3a55-4ad9-aa5e-1808090467a5]: Ansible FAILED! => playbook: setup.yml; TASK: docker/image : Generate certificate; message: {"attempts": 5, "changed": true, "cmd": "docker run --rm -v /opt/rainbond/etc/kubernetes/ssl:/opt/rainbond/etc/kubernetes/ssl -v /opt/rainbond/etc/rbd-api/region.goodrain.me/ssl:/opt/rainbond/etc/rbd-api/region.goodrain.me/ssl -v /opt/rainbond/etc/kubernetes/kubecfg:/opt/rainbond/etc/kubernetes/kubecfg -v /grdata/kubernetes:/grdata/kubernetes rainbond/r6dctl:docker-cfg-certs kip 172.26.1.2", "delta": "0:00:00.746390", "end": "2019-07-23 18:08:51.286622", "msg": "non-zero return code", "rc": 1, "start": "2019-07-23 18:08:50.540232", "stderr": "", "stderr_lines": [], "stdout": "--- /grdata/kubernetes/kube-proxy.kubeconfig\n+++ /opt/rainbond/etc/kubernetes/kubecfg/kube-proxy.kubeconfig\n@@ -1,7 +1,7 @@\n apiVersion: v1\n clusters:\n - cluster:\n- certificate-authority-data:
```

**Comment by olonglongo** [comment]
看报错是执行到ansible-playbook`/opt/rainbond/rainbond-ansible/roles/docker/image/tasks/rsync.yml`中`Generate certificate`任务发生了异常。
请手动执行下`docker run --rm -v /opt/rainbond/etc/kubernetes/ssl:/opt/rainbond/etc/kubernetes/ssl -v /opt/rainbond/etc/rbd-api/region.goodrain.me/ssl:/opt/rainbond/etc/rbd-api/region.goodrain.me/ssl -v /opt/rainbond/etc/kubernetes/kubecfg:/opt/rainbond/etc/kubernetes/kubecfg -v /grdata/kubernetes:/grdata/kubernetes rainbond/r6dctl:docker-cfg-certs kip 172.26.1.2`查看容器状态。

**Comment by linyx-7** [comment]
--- /grdata/kubernetes/kube-proxy.kubeconfig
+++ /opt/rainbond/etc/kubernetes/kubecfg/kube-proxy.kubeconfig
@@ -1,7 +1,7 @@
 apiVersion: v1
 clusters:
 - cluster:
-    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUR2akNDQXFhZ0F3SUJBZ0lVUzhIbTVMaWRmd3ZqczJ1T0x1QVZIdVhwdm1jd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1pURUxNQWtHQTFVRUJoTUNRMDR4RURBT0JnTlZCQWdUQjBKbGFVcHBibWN4RURBT0JnTlZCQWNUQjBKbAphVXBwYm1jeEREQUtCZ05WQkFvVEEyczRjekVQTUEwR0ExVUVDeE1HVTNsemRHVnRNUk13RVFZRFZRUURFd3ByCmRXSmxjbTVsZEdWek1CNFhEVEU1TURjeU5UQXhNRFF3TUZvWERUSTBNRGN5TXpBeE1EUXdNRm93WlRFTE1Ba0cKQTFVRUJoTUNRMDR4RURBT0JnTlZCQWdUQjBKbGFVcHBibWN4RURBT0JnTlZCQWNUQjBKbGFVcHBibWN4RERBSwpCZ05WQkFvVEEyczRjekVQTUEwR0ExVUVDeE1HVTNsemRHVnRNUk13RVFZRFZRUURFd3ByZFdKbGNtNWxkR1Z6Ck1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBcXBHblI2MWlQbnUzRmRESW85djYKeCtmZDB4QUcxMWpMMTJTVTE4KytxR3BkcHF5eXpyc3ZMTkJkTzhIQTJoN1ZTeDZrVWFaU2NQNG11KzhDSW1KWgpYMXdoWVJBTFFSQ3RRYlF3dWQxR0ZNZFNCbXprODNLVGhXc0diSjZ1b05IV3dLSGZINTdhcFJ3bnZydEp4NjU1CnZzZllUTlFiYVF0QUpKaGg0d1lJdkZjOTdjZjNYdHhFTkk0SDJ5d0VBaFk3R1I1blg5RnUzRDhDNWNFeWNhdHEKQmtWRytnVHc0OUNPdGxxVENlYVhVcjlpQWJnbGdSV3FxYyt6bWc1RXVUUHc0cWczZnMvMjNzUnlBbXU1TlJ6dworOWlvazJEVCtxNi9iZEVVc3I0RGpYZkpERVh0ekFGNTUwdVErT3VDZmxJSDB0U0txSEZsNjdPRytpb1cwbHlLCld3SURBUUFCbzJZd1pEQU9CZ05WSFE4QkFmOEVCQU1DQVFZd0VnWURWUjBUQVFIL0JBZ3dCZ0VCL3dJQkFqQWQKQmdOVkhRNEVGZ1FVZ0FtckdEckEvSzdvN1pIeWllUy9ZcW5MNXo0d0h3WURWUjBqQkJnd0ZvQVVnQW1yR0RyQQovSzdvN1pIeWllUy9ZcW5MNXo0d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFBeG1uWjRNQ0xIMmJxWkFhLzdKCmw5RW5rV0M4OFFrRWFqdVhBY2VURjg5OXFpemFKb0NGWEdURzVBVlRnRS9Ia0VhelA4dTlYTnJiYjhsck42MkgKWXZPRzVQbnViNFNNL2dMZVZPUEJwdzZEZEJuZXlpWWFiMEVsZndsVDhOdC9DdWdhZys3QW1Sbnl1MW04K0VXOApmR0oxQTNudFh4SnJxUEFrV2QzQS81WlpsUTlQc2hCQlV1dGZ2S1JKbmowYUVndGl0WTQ2cU52Y2xCbU1NU0dIClVUYkJFZjVZSEh2a1V4N3JkVjhzdGdoRERqVytIVm42dU1TSlZ4OTZKcHMrdGNPYk9VU0RYeDA3UHEzRWR4UGoKN1gxdFlLeGRZNEdKWnlRUHFTcDNUYXBhUHR4TEtndW9oTXErVFNlOUZvSWlkMWxCSWFNR3lsUDdYd3ZGYUJUTApxbnc9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
+    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUR2akNDQXFhZ0F3SUJBZ0lVVzFJZWlGSVVwdjZYM1gxWUR0UDJLRWZKaVlFd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1pURUxNQWtHQTFVRUJoTUNRMDR4RURBT0JnTlZCQWdUQjBKbGFVcHBibWN4RURBT0JnTlZCQWNUQjBKbAphVXBwYm1jeEREQUtCZ05WQkFvVEEyczRjekVQTUEwR0ExVUVDeE1HVTNsemRHVnRNUk13RVFZRFZRUURFd3ByCmRXSmxjbTVsZEdWek1CNFhEVEU1TURjek1EQTRNREV3TUZvWERUSTBNRGN5T0RBNE1ERXdNRm93WlRFTE1Ba0cKQTFVRUJoTUNRMDR4RURBT0JnTlZCQWdUQjBKbGFVcHBibWN4RURBT0JnTlZCQWNUQjBKbGFVcHBibWN4RERBSwpCZ05WQkFvVEEyczRjekVQTUEwR0ExVUVDeE1HVTNsemRHVnRNUk13RVFZRFZRUURFd3ByZFdKbGNtNWxkR1Z6Ck1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBdmt1cURRK3d6NDVINk51NkV5YVMKUjZaL0JLa3UzeXREeit5YVRCODZ0aER6cFpxMjZCajBPbmNFanhaT25zSTRXQTNDcWszVGhJVlFvR0pkWVMwQgpyWWZ3MndkSWEzVjNzNVNneEsvVHRzWVdTQTJYUW1vMmFNYXNrZkFTd05LdjRncEg3QTZxSkhHalg0NXBmVVN0CkRmKzhuZzRHN0FxN3A4cHBHamUyaVpxTnEzajd4dWF1NFplQmdCdCtFR2wxSlhudnNZdG9NMVg5ekZ2dGRNNmQKSnRrN2xVcTJkUWZSS2l3bXRaSlR2UVRvYzVTeHdBUjFzdVN5dGNUT1NvWGk5N2ZZZ09JeHZ1WHkrakNEVmZjMwptYi9uN3JaWmhtMEFsbC9oUWIxc1paMDcxWkN6NlVGYzZkWHJ5R2tMckpLUjJFOU82djVERjF0bUc5aUFTZE9DCnN3SURBUUFCbzJZd1pEQU9CZ05WSFE4QkFmOEVCQU1DQVFZd0VnWURWUjBUQVFIL0JBZ3dCZ0VCL3dJQkFqQWQKQmdOVkhRNEVGZ1FVR2l0R3FFVEV3aW9QbzVZUzdFM3grMzhkTXkwd0h3WURWUjBqQkJnd0ZvQVVHaXRHcUVURQp3aW9QbzVZUzdFM3grMzhkTXkwd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFKQXhqTWR0TzRjRkE1WHM1T3BCCkhrUnY1bTNRWUJrVEdPMkJzZjhsMjNJYWp2Sm5xbXlnRGRMSmxpS1ErRG9McnQ3NFY0OWxSTjhsMjJ5by9UWXkKSndQYUk4WGpnU2tXTkR3UTNPVUNlSXFBRmVCMDFnSTB5VkpxcVVsRE9iWi9qZmpBbkZrd3JDbHQ3aUNSNFJNUwpkVWRrbDBtYlhza1QzRHQ4NmZ2anpZSCtLQTh2c3hFSHFlWTRNdmFxc000VFJtSEpnZ0tWZEhvZG1rUkVZM3RkCm5yRU9SWkIyOHA1MzlwVUdhRWdRWUdRUmJoU1RJR0RKUm44eER2aTBxbVlCeS9SdHp0S3hVSmRickthL2dWL0QKenNjOXhtZmhpdUhZYXZrZWQwaXZRZHpKRmFEbk9lRjZVZnpIWUN0a0FYakwzTURjVGFUL0REZTJEQllzZXUxWAoxc1k9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
     server: https://kubeapi.goodrain.me:6443
   name: kubernetes
 contexts:
@@ -15,5 +15,5 @@
 users:
 - name: kube-proxy
   user:
-    client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUQ0RENDQXNpZ0F3SUJBZ0lVWUxMazV1dE43QW5oZEZDQjR0eElsSklyQVBrd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1pURUxNQWtHQTFVRUJoTUNRMDR4RURBT0JnTlZCQWdUQjBKbGFVcHBibWN4RURBT0JnTlZCQWNUQjBKbAphVXBwYm1jeEREQUtCZ05WQkFvVEEyczRjekVQTUEwR0ExVUVDeE1HVTNsemRHVnRNUk13RVFZRFZRUURFd3ByCmRXSmxjbTVsZEdWek1DQVhEVEU1TURjeU5UQXhNRFF3TUZvWUR6SXhNVGt3TnpBeE1ERXdOREF3V2pCc01Rc3cKQ1FZRFZRUUdFd0pEVGpFUU1BNEdBMVVFQ0JNSFFtVnBTbWx1WnpFUU1BNEdBMVVFQnhNSFFtVnBTbWx1WnpFTQpNQW9HQTFVRUNoTURhemh6TVE4d0RRWURWUVFMRXdaVGVYTjBaVzB4R2pBWUJnTlZCQU1URVhONWMzUmxiVHByCmRXSmxMWEJ5YjNoNU1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBMGEyNktId3IKemd2bi93b0crYTc5LzVGakNtT3ZWN3RGZTJKTTdRWitGaEZ3T202Y3NidDMyVnFXYkhwTnBDN3V1MWJzd2puYQpkVHNITjBsUkVMaUI1LzViS29SYURKam54L3RhaE54T2Z0cytVZ2UyMEdwd1lEVzluQzdSOUo4U2l5bTVObVFiCklld3RKVzhhbUIvVW94QTdyT3B3MDlXQ2ZwYk01cnJKdk5VNUN2MCtubEJsMEJhRi9vbHdaVnJaWUZ4UVQxUlYKRVVVRitTelFSdXJvR0Z4VEpUZk9MQ2pRUTJhL3pkdnVKN2RaOG8xbEVjcFZmR3J6c0hlT25vcXdETFZGTklwRgpnTEIzaVB1bjBqODNmc2JQWWl4SitTTmp2ZU9DTEVXWWJyQUhOMEtVa2Q4R1E5YXZnY1hHWlR1MFRnRyt0cHdpClNUZm1mOXdMQTNmN0NRSURBUUFCbzM4d2ZUQU9CZ05WSFE4QkFmOEVCQU1DQmFBd0hRWURWUjBsQkJZd0ZBWUkKS3dZQkJRVUhBd0VHQ0NzR0FRVUZCd01DTUF3R0ExVWRFd0VCL3dRQ01BQXdIUVlEVlIwT0JCWUVGT0s3emEzUgpzS1Y3N1JEVzVxcDEvRmVncUxyY01COEdBMVVkSXdRWU1CYUFGSUFKcXhnNndQeXU2TzJSOG9ua3YyS3B5K2MrCk1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQ0JPSmw4VFJZQXRYWTB1T0M2M25CeUI0Kys1eUIyL3UxZEQ2V0YKMTVMRzdzQlNpU2YwZCtzZlFaOFVwRm9PcUI1MXV0aVZzS0dDTCtpYXR5K0RRaWlKVzdOTmZFWjdrVXZYT1hBSwpWWi9Dck1uemV6R1pZdzVxbWhSNVFDOC9zeUFUdEtEUWdhTVVPZkYvMVdQUEhyMmNiYVJIVGJLTXVlckx4YUNzCk9IcUFqMWFKSkdYdDE5NjFoM2owcytRVWQzQXF3S2xHcUFqWmVRRXJrU0kvYU5tMVh2RjFHUU1ZSTJzeStqek8KcjNYSFdtbEQzVjlmZEE4RFhwNndvdlNFUENtWG1BdlMwVjNDNHpKT0s0eGh2ZW11T1RPVEpUeUdnMnRJanRKegp2bXdiR2FxWWxJNk1rajlKdVJSTkh5NnptRExaUkJ0Ujc1elg4ZzJBQUxrNWJtZWgKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
-    client-key-data: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBMGEyNktId3J6Z3ZuL3dvRythNzkvNUZqQ21PdlY3dEZlMkpNN1FaK0ZoRndPbTZjCnNidDMyVnFXYkhwTnBDN3V1MWJzd2puYWRUc0hOMGxSRUxpQjUvNWJLb1JhREpqbngvdGFoTnhPZnRzK1VnZTIKMEdwd1lEVzluQzdSOUo4U2l5bTVObVFiSWV3dEpXOGFtQi9Vb3hBN3JPcHcwOVdDZnBiTTVyckp2TlU1Q3YwKwpubEJsMEJhRi9vbHdaVnJaWUZ4UVQxUlZFVVVGK1N6UVJ1cm9HRnhUSlRmT0xDalFRMmEvemR2dUo3ZFo4bzFsCkVjcFZmR3J6c0hlT25vcXdETFZGTklwRmdMQjNpUHVuMGo4M2ZzYlBZaXhKK1NOanZlT0NMRVdZYnJBSE4wS1UKa2Q4R1E5YXZnY1hHWlR1MFRnRyt0cHdpU1RmbWY5d0xBM2Y3Q1FJREFRQUJBb0lCQUhtLzdJWXhnNllDMTlVSgpWMytIa3NqZy9LYzl0c1MwWXVYLzhEYjVQQ0ZJUXVoSzdnVnRtMnZENC9CZEc5UW54RXRYYitaZmZXL3d0SUh2CnVuaUJDajFSUGxKencyM3BJenpGd0l2QStIdEVodTFPdVdKUFM2MHh4MFYzRWtaK1QyQXErL2FQTGdvR2Z6aHIKU1Avb0M2b2JkT3MwdmdyaXdRRU1RekgrWjhHUzUvL0EyK0VsWHAxK29kRDRuYitNcVlTSUlWbldYQWdMSzVkNQpkbm41ZDZIL0hLWWQrK1E0ZXprcGdVSHZEdGJyRkthUVkwbUkwK1d6YzFSL1l3SFowMlNzdEx1cXJIeDBqaFl4CmloeVFEd1JXTndsNE5PcE5iTE1UUXQ5T1VNbDk0MWFhN203MFZ1aEt5NnA5Um1VcThybnlZSmJKb3QxZ0V3a0IKN1ZEdDQva0NnWUVBOThvUWhjRFBJZG5GRlZQRDhjMC90TG9ZYVl1RlQ4ZytuTVN3ZTluWmFGZ0NFUW43aHhQcQpaa1BnMFNHUnNySnE4Y3VlbnpWRGtCSWZYL1FENlhienE0T3VPNzEyNGlXNEpvRVVYODhmNkxGWG80ZkFNdU9ZCjV0MTZnWmJUVVJKUmZkdHhJaDhlMDF1STlqNkF2Vnl3bUV0Mk1yMHRvcFZVMXFPdm9YQlI0KzhDZ1lFQTJLQmgKQ2hCQ3Q0RVJFSXppenFKZWZWSUt3cnZZZEFONzJFZ1U5VzFaN1hhb0sxVS9UaEFUQ2svSngrYVdJMERybmh0MgpZZWh5U0o3ZDJTS1lEbmY1cjJRem9SOWJJSGNSenkwRGZsUGNxNUdzbStzY2FONzYvUFh3RHo3VTFUTTc4SFVxCkxFVWZBNXhDcWhCZFhsOXBGV0pmNGhOaVRFSlMrV2thaEFIYnVJY0NnWUVBb1g5blNXV2pHckx1aXJudnFiZFcKWUJveU13Z21PUnVRQTJrR2haSTA2cGNCc2MxSnpINGtkY2Fqem1vTXBlVTNZcVNObThLQmFITUhVK2ljYkJ1RgpNVEkvNnR2UGtoRjNkbEVHMEhNVW52cUczaVJxRmtEVXRST0E5dGt3blZSTkhMUmJoaHUyWVpiMUsxa05XMTRBCkV5S0x4UUlicmkyWi85THJjMUxiYkswQ2dZRUEwVGdVZ09PempBZmJzMkJlcmJPa0R1VnQveVh0cUI2MVBlNWcKVDZtTmNRdG80SEUwOHZBVGM2SWNBRFYwVEJnbmVFeU55WUgyM3F5UkYyV1I5bWRwZnp3SG9WWG5iVE9TdjhWNQoya2lrbUEvWjVienRjMXZvak9mN01yNDhVSzFxOXBJeWFROVpKT09HZnpuTzg1YXlwelNiNW4xU010VGJ6b2IwClZRcDJhNEVDZ1lCTmswVUhGUWpOaXowRC9yQjBKSm5MMDlEN2psQWVGVzBQb2tjdXE1NUd0cWZ0RVhPVWhEWWUKeTE5VkhZeEVMbUx4bjA5bCt6MitBdDVMSlU0MHBoVDFSeHY0ZVE4UU5PRVRUQ2VvTFd0SHhGcUV4QU5UQVZCYgpXR0RRKzFtQnFvOWV5UmdXT1pXVEtaTkZhaU45cHgyWjFuSnRielBObHY5MHNUQnh4ODQrNGc9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
+    client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUQ0RENDQXNpZ0F3SUJBZ0lVWkJ5MWIyTjNBYVdic1JCTkEwOHhGYURVcXZnd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1pURUxNQWtHQTFVRUJoTUNRMDR4RURBT0JnTlZCQWdUQjBKbGFVcHBibWN4RURBT0JnTlZCQWNUQjBKbAphVXBwYm1jeEREQUtCZ05WQkFvVEEyczRjekVQTUEwR0ExVUVDeE1HVTNsemRHVnRNUk13RVFZRFZRUURFd3ByCmRXSmxjbTVsZEdWek1DQVhEVEU1TURjek1EQTRNREV3TUZvWUR6SXhNVGt3TnpBMk1EZ3dNVEF3V2pCc01Rc3cKQ1FZRFZRUUdFd0pEVGpFUU1BNEdBMVVFQ0JNSFFtVnBTbWx1WnpFUU1BNEdBMVVFQnhNSFFtVnBTbWx1WnpFTQpNQW9HQTFVRUNoTURhemh6TVE4d0RRWURWUVFMRXdaVGVYTjBaVzB4R2pBWUJnTlZCQU1URVhONWMzUmxiVHByCmRXSmxMWEJ5YjNoNU1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBbmxhVW5ZRFkKbzRpMlRUeFpKZHRaNDRkQzlrU1NQNW10UWJXODBhaVQyUFl2Vi9oQ3hWOHhQcGpiK1pJeHVmNGVwK1g0aEkvSwo1OXFtbU9ZZTV4M3U0cTlPTkp6UDQvbEFST0JNOFpTUHFMWlE5ZzdPMGxJU0Vtd2xoWThZNE5TQ0ZUeFZXeUczCk9TUTdSS2JITlRSMFVjaEVhV0J4MFlQWTZkVkduc014ZzZEajUrbUpsODdlNU96MHJwWEJuNGNNU2t0T29qV2UKekZDVGhYdGh0ZnBiM2VNVnZqeWduY21pekJCRDBTRFpJSyt1U2RNOGNaWkNTVUVTWVhORllYM2NIcDdYSFpINQp5d2FGd0hQcUsyYmF3U3FhNnkydWpRcGkzckNYWkw4TTN6L1B4d2h4SXpxQ0FJNWpONWdXamFJUFBXVjdEdGdWCnlqVnJ4Z050SG9wU3d3SURBUUFCbzM4d2ZUQU9CZ05WSFE4QkFmOEVCQU1DQmFBd0hRWURWUjBsQkJZd0ZBWUkKS3dZQkJRVUhBd0VHQ0NzR0FRVUZCd01DTUF3R0ExVWRFd0VCL3dRQ01BQXdIUVlEVlIwT0JCWUVGSWlkakR0bQpXeWM4VmRpaHZmbVI5UjRpek9qNE1COEdBMVVkSXdRWU1CYUFGQm9yUnFoRXhNSXFENk9XRXV4TjhmdC9IVE10Ck1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQkkzdWhWV3ZhRXJHM1B5VGNadjNvSzhjK3hLNzJQTHMvdGQzdE8KZVdsZGQ1OVJPTlBvdFRvcUl1YnVYdzNhL2R3UzZudGRTNXJJbGlCRXJ0Kzh0V3lCZGZiNFZvdDQ0TEdnVXNzKwpwU29zaHU2MW9YNmFDcmUvd0J3a21tcXVyUjc3Qm5LbXA5UElzdk8xTHlLcmNZRjRQOGpTN3dvblBtdWI5ZGpuCmJ2R0t1bjVyaldia0JWTDd1UU04VkJNNE9xVzh5bHpoNVk3OURTKzMrVWE2RzIxeng1NjlJMlFNVUEvb0RCVDQKM1hZc0NjdWFUdklJTmcyT3RvYjZaYkpPYi9vYTNDNUh5MS91MzhaSENIM1c4cVY1dTFRL0NseDdubVNuT3VFYQpYUW9pdHYvQWFSdFFhUkJxazBaUTV0RnZzRURQK2x1WkxQR0Y0UFV5M2xReTlSWU8KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
+    client-key-data: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb2dJQkFBS0NBUUVBbmxhVW5ZRFlvNGkyVFR4WkpkdFo0NGRDOWtTU1A1bXRRYlc4MGFpVDJQWXZWL2hDCnhWOHhQcGpiK1pJeHVmNGVwK1g0aEkvSzU5cW1tT1llNXgzdTRxOU9OSnpQNC9sQVJPQk04WlNQcUxaUTlnN08KMGxJU0Vtd2xoWThZNE5TQ0ZUeFZXeUczT1NRN1JLYkhOVFIwVWNoRWFXQngwWVBZNmRWR25zTXhnNkRqNSttSgpsODdlNU96MHJwWEJuNGNNU2t0T29qV2V6RkNUaFh0aHRmcGIzZU1Wdmp5Z25jbWl6QkJEMFNEWklLK3VTZE04CmNaWkNTVUVTWVhORllYM2NIcDdYSFpINXl3YUZ3SFBxSzJiYXdTcWE2eTJ1alFwaTNyQ1haTDhNM3ovUHh3aHgKSXpxQ0FJNWpONWdXamFJUFBXVjdEdGdWeWpWcnhnTnRIb3BTd3dJREFRQUJBb0lCQUJ6VnlhVFJWU0tiQUJBYQp3R1ZyaC9ndXB0d3dhcTNZYjd2NnU5TTJydzRnNzBoRzl1bjR4d0FPV0drZjNaeHdrZWFqczlsNFVreGMvbC96CjhJYklaYnUwanpwM29FaDFHT1l5THZFRHpCRytlZ29GY2xiTkNXdC9kR25aUUgrWlU4TklSSWNmSWIzdlFqZmoKWTMzbCtwVDJNcmM2RUNCR3NaY0w5eHRza3JUVXE3Rkx3ci81QUZ4RUlPeitpZEZtWE0xQ0pvTXBNUUkyT3BTOApSQm1ZejVJTDgwNzFic2lPc3cyblFYZG5uSk5UVWNtKytwbGFNQTF6UlhUSVVQV3VpTlNoQ3ZnWHpxRzVMTWpzCmV0SlVvUTFleHFsYjdlZ1lNZVhRa1B3RFdDZW9EYk5mRG9GMEU2a2hLQzBmUGhMOXF2b0Q3RDFOeWhRSzgxMCsKdDZ2dUQ5a0NnWUVBeEE1cmxIY2dKQ1p2T0J5aFNPMWhFZ3A5TDdtRnc1RkVFclQyamVaMmtmcDVqMGlVSHJZNApHd1FMU2lqaDgwdFZibkNhTDFJVEg0dG5ZRUpadFhEcFNCUVN5U3lxbC9XR0w0SnVFM0lCMlkzdXFic3pyMDVTCmVaMU9VTEsyOWxIOE8zdGdSRWk2Y1EvL0JNZkJsdWxDYWZJaFNKYmtOTWVVZElTUU05M0lqazhDZ1lFQXpyL3EKR3VKdy9aaTFRK241VFRnVFJPeFRITmZWZnlPa2J6K0YvVHVKVnloczh4VDRKN0FuYlkvOGxmMFRyV3dxbGcyQQpGYXlpR2FJaGNrbGNPNThyT296Z2lBSGdEV1cxNkNsR2c3ZjRIbVNYMmtiRHhGZ1hUQjIwRVVZUnNhRythYnNICkxZSHNObEpmcmhncUswRXlVdFBROFlPNlVscG1TdTBRNFIvYjYwMENnWUJDczhsRUxMZGh0VFhYdUYzakt1Z0EKdEZMZEh0aDByZ0tqL3E5M25iWXZlakZMWDEwTmlkOVN5YkJ4bmJFcURqSlZyYmUzYTh3WHlsejBjZjZGYlpIZwp0UHVqT0RBZUhTbDNGb0FPMjVYbmg1TndhY0Z1M2szUEZJYmxpN2dWMjlUZUE5Ni92S0s1L3NBN3h4NkZFbjFICkFGcjBrR201ejBFaDEwd2NhVk5ubndLQmdGZTNhcjUvUmdzQjZCM3BQY0U2UWtxaXJWeDJZZmt3Q1FxOSs3NEYKclc1U0UyOUtmVUp4WlRrQnR0dDM1UXBWOHZkNHdOZnhSMUR5elpmc2NmcEZ2SlI1d3FWUmpscUF4WjI3TFZTagpEOXp0TnRQLzQvMEFsdG5QWEY5YnlCUUNHSVJKT25GZlJ2V0JHMkVFbFplR2NMQmRkNitRQU5RQjBKYUhYL3J6CmhsMmRBb0dBZHdlSDBjZ2tMVmsyMVlORXdtOGtmRWpEYlZkVDVSSnFRUTFIMGFLakY5WU5IWmd1WU5wRzEzcTkKUFF4alcrckdjTnR4bGhpZTZvWUJnaGRrVHBrNGwzYkZmUVpnYmJjRy9lcDV6VlNheGNqNDQ1akVqQmdONXdITQpFbjh5YXJFZ08vZEFEVU80SSs5S25MQ1Z0Q29BV2ZSY2NIaHhXTzZvYmFXYkNUZEo5Z1k9Ci0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
上次重新安装后成功一次，这次安装又失败。

**Comment by barnettZQG** [comment]
这种情况应该是多次使用了同一个NAS存储导致的。建议做以下处理：
删除 /grdata 中数据和/opt/rainbond的数据重新安装。
