### ISSUE TITLE
阿里云在线安装报错

### ISSUE THREAD

**Issue by linyx-7** [goodrain/rainbond-ansible#92]
请提供如下信息：
- 安装环境信息(云服务商或者本地虚拟环境，系统版本，内核版本，配置信息等)阿里云centos 7.4
- 安装类型(单机,离线,使用版本信息等)在线安装5.1.5
- ansible安装日志 (`/opt/rainbond/rainbond-ansible/log/`)2019-07-24 14:59:57,993 p=14516 u=root |  [98b0fdca-4a27-444d-b567-26b8f12d0cc8]: Ansible FAILED! => playbook: setup.yml; TASK: node/up : Rainbond | Push local images to goodrain.me; message: {"attempts": 5, "changed": true, "cmd": "bash /tmp/install/pushimage.sh > /tmp/install/pushimage.log", "delta": "0:01:00.895585", "end": "2019-07-24 14:59:57.966129", "msg": "non-zero return code", "rc": 1, "start": "2019-07-24 14:58:57.070544", "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}

- 能否复现，如何复现
- 如果可以提供相关截图
![image](https://user-images.githubusercontent.com/53252563/61772709-8763d300-ae25-11e9-9cfb-cedc0231dac2.png)

**Comment by barnettZQG** [comment]
@linyx-7 
由于golang 基础编译镜像有变更导致Rainbond最新版本安装包出现故障。现安装包已重新更新，请尝试重新安装。

**Comment by barnettZQG** [comment]
我将关闭此问题，如果还有故障请重新打开
