### ISSUE TITLE
ubuntu16快速安装失败

### ISSUE THREAD

**Issue by hh1202** [goodrain/rainbond-ansible#95]
请提供如下信息：
- 安装环境信息：本地虚拟机vmware15安装ubuntu16
- 安装类型(单机,离线,使用版本信息等) 快速安装，使用版本v5.1.5
./grctl init --iip <内网ip /内部IP > --eip <外网ip /外部IP >运行后出现错误
  可以复现，安装三次以及是这样
![image](https://user-images.githubusercontent.com/48941077/61844294-7e304000-aed1-11e9-8b63-20de88f957a3.png)

**Comment by olonglongo** [comment]
我们的脚本已经修改了安装逻辑(同一个节点只能安装一次)，请使用最新的脚本重新安装。
<img width="962" alt="image" src="https://user-images.githubusercontent.com/37605428/61853253-0d4b5100-aeee-11e9-8aba-773afe4cf8dd.png">

**Comment by hh1202** [comment]
但是5.1.5不就是最新的版本吗
![image](https://user-images.githubusercontent.com/48941077/61857260-5d2e1600-aef6-11e9-8afe-5a211e826b8c.png)

**Comment by hh1202** [comment]
![image](https://user-images.githubusercontent.com/48941077/61857282-6919d800-aef6-11e9-8287-00712637cd36.png)

**Comment by barnettZQG** [comment]
@hh1202  有什么疑问吗？
